import Head from "next/head";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";
import Become from "@/components/Become";
import Students from "@/components/Students";
import Education from "@/components/Education";
import Program from "@/components/Program";
import Visit from "@/components/Visit";
import Impact from "@/components/Impact";
import Ukraine from "@/components/Ukraine";
import News from "@/components/News";
import Calendar from "@/components/Calendar";
import Amsterdam from "@/components/Amsterdam";
import Tour from "@/components/Tour";
import Footer from "@/components/Footer";
import Menu from "@/components/Menu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vrigie universiteit Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        {/* <Navbar /> */}
        <Become />
      </Wrapper>
      <Students />
      <Wrapper>
        <Education />
        <Program />
        <Visit />
        <Impact />
        <Ukraine />
        <News />
        <Calendar />
        <Visit />
        <Amsterdam />
        <Tour />
        <Menu />
        {/* <Footer /> */}
      </Wrapper>
    </>
  );
}
